CREATE OR REPLACE TRIGGER DISP_DETALLEPEDIDOS
BEFORE INSERT OR UPDATE 
ON E_DETALLEPEDIDOS 
FOR EACH ROW

DECLARE
CURSOR C_PEDIDOS (P_COD_PEDIDO IN NUMBER) IS 
SELECT DISTINCT P.CODIGOPRODUCTO, P.CANTIDADENSTOCK, D.UNIDADESPEDIDAS, P.CANTIDADENSTOCK-D.UNIDADESPEDIDAS "STOCK_TRAS_PEDIDO"
FROM E_DETALLEPEDIDOS D, E_PRODUCTOS P
WHERE P.CODIGOPRODUCTO=D.CODIGOPRODUCTO AND D.CODIGOPEDIDO='P_COD_PEDIDO' --Utilizamos el parámetro definido en la declaración del cursor
ORDER BY P.CODIGOPRODUCTO;

BEGIN
  FOR R_PEDIDOS IN C_PEDIDOS('P_COD_PEDIDO') LOOP
  IF (R_PEDIDOS.STOCK_TRAS_PEDIDO<0) THEN --Si el stock tras el pedido es menor a cero saltará el error
  RAISE_APPLICATION_ERROR(-105, 'No hay stock suficiente para cubrir este pedido');
  END IF;
END LOOP;

END;